import 'word_bank_entry.dart';

/// All 99 Names of Allah (Asma-ul-Husna). [WordEntry.word] drops hyphens
/// and apostrophes so it fits a word-search grid as a single token (e.g.
/// "ARRAHMAN"); [WordEntry.displayName] keeps the standard transliteration.
///
/// The exact sequence/numbering of the 99 names varies slightly across
/// published scholarly lists (the Qur'an and authentic hadith establish
/// that Allah has 99 names without fixing one canonical numbered order) —
/// this list draws on the standard, widely-published enumeration. Every
/// name/meaning pairing here is a good-faith best effort and, being
/// religious content, is worth a scholarly spot-check before being treated
/// as authoritative.
const kNamesOfAllah = <WordEntry>[
  WordEntry('ARRAHMAN', 'Ar-Rahman',
      'The Most Merciful — mentioned at the start of nearly every Surah in the Qur\'an.',
      'الرحمن'),
  WordEntry('ARRAHEEM', 'Ar-Raheem',
      'The Most Compassionate — His special mercy shown to the believers.',
      'الرحيم'),
  WordEntry('ALMALIK', 'Al-Malik',
      'The King — the true Sovereign over all creation.',
      'الملك'),
  WordEntry('ALQUDDUS', 'Al-Quddus',
      'The Most Holy — utterly free from any imperfection.',
      'القدوس'),
  WordEntry('ASSALAM', 'As-Salam',
      'The Source of Peace — from whom all safety and peace flow.',
      'السلام'),
  WordEntry('ALMUMIN', 'Al-Mu\'min',
      'The Granter of Security — gives faith and safety to His creation.',
      'المؤمن'),
  WordEntry('ALMUHAYMIN', 'Al-Muhaymin',
      'The Guardian — watches over and protects all that exists.',
      'المهيمن'),
  WordEntry('ALAZIZ', 'Al-Aziz',
      'The Almighty — the One whose might can never be overcome.',
      'العزيز'),
  WordEntry('ALJABBAR', 'Al-Jabbar',
      'The Compeller — none can resist what He wills.',
      'الجبار'),
  WordEntry('ALMUTAKABBIR', 'Al-Mutakabbir',
      'The Supreme in Greatness — greatness belongs to Him alone.',
      'المتكبر'),
  WordEntry('ALKHALIQ', 'Al-Khaliq',
      'The Creator — brings all things into existence from nothing.',
      'الخالق'),
  WordEntry('ALBARI', 'Al-Bari\'',
      'The Evolver — shapes creation with perfect proportion.',
      'البارئ'),
  WordEntry('ALMUSAWWIR', 'Al-Musawwir',
      'The Fashioner — gives every created thing its unique form.',
      'المصور'),
  WordEntry('ALGHAFFAR', 'Al-Ghaffar',
      'The Ever-Forgiving — forgives the sins of His servants again and again.',
      'الغفار'),
  WordEntry('ALQAHHAR', 'Al-Qahhar',
      'The Subduer — holds total dominance over all things.',
      'القهار'),
  WordEntry('ALWAHHAB', 'Al-Wahhab',
      'The Bestower — gives generously without expecting anything in return.',
      'الوهاب'),
  WordEntry('ARRAZZAQ', 'Ar-Razzaq',
      'The Provider — sustains every living creature.',
      'الرزاق'),
  WordEntry('ALFATTAH', 'Al-Fattah',
      'The Opener — opens the way to relief, victory, and understanding.',
      'الفتاح'),
  WordEntry('ALALEEM', 'Al-Aleem',
      'The All-Knowing — nothing in creation escapes His knowledge.',
      'العليم'),
  WordEntry('ALQABID', 'Al-Qabid',
      'The Withholder — restricts provision and ease as He wills.',
      'القابض'),
  WordEntry('ALBASIT', 'Al-Basit',
      'The Extender — expands provision and ease as He wills.',
      'الباسط'),
  WordEntry('ALKHAFID', 'Al-Khafid',
      'The Abaser — humbles the arrogant and unjust.',
      'الخافض'),
  WordEntry('ARRAFI', 'Ar-Rafi\'',
      'The Exalter — raises up whoever He wills in honor.',
      'الرافع'),
  WordEntry('ALMUIZZ', 'Al-Mu\'izz',
      'The Honorer — grants honor to whoever He wills.',
      'المعز'),
  WordEntry('ALMUDHILL', 'Al-Mudhill',
      'The Humiliator — brings low whoever He wills.',
      'المذل'),
  WordEntry('ASSAMI', 'As-Sami\'',
      'The All-Hearing — hears every voice and every silent thought.',
      'السميع'),
  WordEntry('ALBASEER', 'Al-Baseer',
      'The All-Seeing — nothing in creation is hidden from His sight.',
      'البصير'),
  WordEntry('ALHAKAM', 'Al-Hakam',
      'The Judge — the final authority in every matter.',
      'الحكم'),
  WordEntry('ALADL', 'Al-Adl',
      'The Utterly Just — never wrongs anyone in the slightest.',
      'العدل'),
  WordEntry('ALLATEEF', 'Al-Lateef',
      'The Subtle One — aware of the finest, most hidden details of everything.',
      'اللطيف'),
  WordEntry('ALKHABIR', 'Al-Khabir',
      'The All-Aware — fully informed of the reality of all things.',
      'الخبير'),
  WordEntry('ALHALEEM', 'Al-Haleem',
      'The Forbearing — remains gentle with His servants despite their shortcomings.',
      'الحليم'),
  WordEntry('ALAZEEM', 'Al-Azeem',
      'The Magnificent — His greatness has no limit.',
      'العظيم'),
  WordEntry('ALGHAFUR', 'Al-Ghafur',
      'The Great Forgiver — covers and pardons sin generously.',
      'الغفور'),
  WordEntry('ASHSHAKUR', 'Ash-Shakur',
      'The Most Appreciative — rewards even small acts of good abundantly.',
      'الشكور'),
  WordEntry('ALALIYY', 'Al-Aliyy',
      'The Most High — exalted above all of His creation.',
      'العلي'),
  WordEntry('ALKABIR', 'Al-Kabir',
      'The Most Great — greater than anything that can be imagined.',
      'الكبير'),
  WordEntry('ALHAFEEZ', 'Al-Hafeez',
      'The Preserver — protects and safeguards all that He has created.',
      'الحفيظ'),
  WordEntry('ALMUQEET', 'Al-Muqeet',
      'The Sustainer — provides the nourishment every creature needs.',
      'المقيت'),
  WordEntry('ALHASEEB', 'Al-Haseeb',
      'The Reckoner — takes account of every deed with perfect precision.',
      'الحسيب'),
  WordEntry('ALJALEEL', 'Al-Jaleel',
      'The Majestic — possesses greatness and honor beyond compare.',
      'الجليل'),
  WordEntry('ALKARIM', 'Al-Karim',
      'The Most Generous — gives abundantly and honors His creation.',
      'الكريم'),
  WordEntry('ARRAQEEB', 'Ar-Raqeeb',
      'The Watchful — observes every creature at every moment.',
      'الرقيب'),
  WordEntry('ALMUJEEB', 'Al-Mujeeb',
      'The Responsive One — answers the call of whoever turns to Him.',
      'المجيب'),
  WordEntry('ALWASI', 'Al-Wasi\'',
      'The All-Encompassing — His mercy and knowledge embrace all things.',
      'الواسع'),
  WordEntry('ALHAKEEM', 'Al-Hakeem',
      'The All-Wise — every command and decree carries perfect wisdom.',
      'الحكيم'),
  WordEntry('ALWADUD', 'Al-Wadud',
      'The Most Loving — loves His righteous servants deeply.',
      'الودود'),
  WordEntry('ALMAJEED', 'Al-Majeed',
      'The Most Glorious — glorious in both His essence and His deeds.',
      'المجيد'),
  WordEntry('ALBAITH', 'Al-Ba\'ith',
      'The Resurrector — will raise all creation on the Day of Judgment.',
      'الباعث'),
  WordEntry('ASHSHAHEED', 'Ash-Shaheed',
      'The Witness — witnesses everything, everywhere, at all times.',
      'الشهيد'),
  WordEntry('ALHAQQ', 'Al-Haqq',
      'The Absolute Truth — the ultimate, unchanging reality.',
      'الحق'),
  WordEntry('ALWAKEEL', 'Al-Wakeel',
      'The Trustee — the One relied upon to arrange every affair.',
      'الوكيل'),
  WordEntry('ALQAWIYY', 'Al-Qawiyy',
      'The Most Strong — His strength has no limit or weakness.',
      'القوي'),
  WordEntry('ALMATEEN', 'Al-Mateen',
      'The Firm One — perfectly steady and unshakeable in power.',
      'المتين'),
  WordEntry('ALWALIYY', 'Al-Waliyy',
      'The Protecting Friend — supports and protects the believers.',
      'الولي'),
  WordEntry('ALHAMEED', 'Al-Hameed',
      'The Praiseworthy — worthy of all praise in every circumstance.',
      'الحميد'),
  WordEntry('ALMUHSI', 'Al-Muhsi',
      'The All-Enumerating — keeps a perfect count of every single thing.',
      'المحصي'),
  WordEntry('ALMUBDI', 'Al-Mubdi\'',
      'The Originator — began all of creation without any prior example.',
      'المبدئ'),
  WordEntry('ALMUEED', 'Al-Mu\'eed',
      'The Restorer — will bring creation back after it ends.',
      'المعيد'),
  WordEntry('ALMUHYI', 'Al-Muhyi',
      'The Giver of Life — brings the lifeless to life.',
      'المحيي'),
  WordEntry('ALMUMEET', 'Al-Mumeet',
      'The Bringer of Death — decrees the end of every living thing.',
      'المميت'),
  WordEntry('ALHAYY', 'Al-Hayy',
      'The Ever-Living — living with a life that never ends.',
      'الحي'),
  WordEntry('ALQAYYUM', 'Al-Qayyum',
      'The Self-Subsisting Sustainer — depends on nothing, while all else depends on Him.',
      'القيوم'),
  WordEntry('ALWAJID', 'Al-Wajid',
      'The Perceiver — finds and knows all things without any effort.',
      'الواجد'),
  WordEntry('ALWAHID', 'Al-Wahid',
      'The One — one without any partner or equal.',
      'الواحد'),
  WordEntry('ASSAMAD', 'As-Samad',
      'The Eternal Refuge — the One all creation turns to in need.',
      'الصمد'),
  WordEntry('ALQADIR', 'Al-Qadir',
      'The All-Powerful — capable of absolutely anything He wills.',
      'القادر'),
  WordEntry('ALMUQTADIR', 'Al-Muqtadir',
      'The Creator of All Power — holds total power over all things.',
      'المقتدر'),
  WordEntry('ALMUQADDIM', 'Al-Muqaddim',
      'The Expediter — brings forward whoever and whatever He wills.',
      'المقدم'),
  WordEntry('ALMUAKHKHIR', 'Al-Mu\'akhkhir',
      'The Delayer — holds back whoever and whatever He wills.',
      'المؤخر'),
  WordEntry('ALAWWAL', 'Al-Awwal',
      'The First — existed before anything else came to be.',
      'الأول'),
  WordEntry('ALAKHIR', 'Al-Akhir',
      'The Last — will remain after everything else ends.',
      'الآخر'),
  WordEntry('AZZAHIR', 'Az-Zahir',
      'The Manifest — His existence is evident in all of creation.',
      'الظاهر'),
  WordEntry('ALBATIN', 'Al-Batin',
      'The Hidden — His true essence is beyond human perception.',
      'الباطن'),
  WordEntry('ALWALI', 'Al-Wali',
      'The Governor — manages and directs the affairs of all creation.',
      'الوالي'),
  WordEntry('ALMUTAALI', 'Al-Muta\'ali',
      'The Most Exalted — far above any imperfection or limitation.',
      'المتعالي'),
  WordEntry('ALBARR', 'Al-Barr',
      'The Source of All Goodness — kind and generous to His creation.',
      'البر'),
  WordEntry('ATTAWWAB', 'At-Tawwab',
      'The Ever-Relenting — constantly accepts the repentance of His servants.',
      'التواب'),
  WordEntry('ALMUNTAQIM', 'Al-Muntaqim',
      'The Avenger — brings just consequence upon persistent wrongdoing.',
      'المنتقم'),
  WordEntry('ALAFUWW', 'Al-Afuww',
      'The Pardoner — erases sins entirely for those who repent.',
      'العفو'),
  WordEntry('ARRAUF', 'Ar-Ra\'uf',
      'The Most Kind — shows tender kindness beyond ordinary mercy.',
      'الرؤوف'),
  WordEntry('MALIKULMULK', 'Malik-ul-Mulk',
      'Owner of All Sovereignty — all dominion belongs to Him alone.',
      'مالك الملك'),
  WordEntry('DHULJALALIWALIKRAM', 'Dhul-Jalali wal-Ikram',
      'Lord of Majesty and Honor — deserving of the greatest glory and reverence.',
      'ذو الجلال والإكرام'),
  WordEntry('ALMUQSIT', 'Al-Muqsit',
      'The Equitable One — establishes perfect justice between all things.',
      'المقسط'),
  WordEntry('ALJAMI', 'Al-Jami\'',
      'The Gatherer — will bring all of creation together on the Day of Judgment.',
      'الجامع'),
  WordEntry('ALGHANI', 'Al-Ghani',
      'The Self-Sufficient — needs nothing from anyone or anything.',
      'الغني'),
  WordEntry('ALMUGHNI', 'Al-Mughni',
      'The Enricher — frees His creation from need.',
      'المغني'),
  WordEntry('ALMANI', 'Al-Mani\'',
      'The Preventer — withholds harm and hardship from whoever He wills.',
      'المانع'),
  WordEntry('ADDARR', 'Ad-Darr',
      'The One Who Allows Harm — permits hardship as a trial or consequence, by His wisdom.',
      'الضار'),
  WordEntry('ANNAFI', 'An-Nafi\'',
      'The Bringer of Benefit — the true source of every good that reaches His creation.',
      'النافع'),
  WordEntry('ANNUR', 'An-Nur',
      'The Light — the Light of the heavens and the earth.',
      'النور'),
  WordEntry('ALHADI', 'Al-Hadi',
      'The Guide — leads His creation toward truth and the right path.',
      'الهادي'),
  WordEntry('ALBADI', 'Al-Badi\'',
      'The Incomparable Originator — creates without any precedent to copy.',
      'البديع'),
  WordEntry('ALBAQI', 'Al-Baqi',
      'The Everlasting — will remain forever after all else passes away.',
      'الباقي'),
  WordEntry('ALWARITH', 'Al-Warith',
      'The Ultimate Inheritor — all that remains returns to Him alone.',
      'الوارث'),
  WordEntry('ARRASHEED', 'Ar-Rasheed',
      'The Guide to the Right Path — leads all things to their proper end with perfect wisdom.',
      'الرشيد'),
  WordEntry('ASSABUR', 'As-Sabur',
      'The Most Patient — never rushes to punish, giving time to repent.',
      'الصبور'),
  WordEntry('ALAHAD', 'Al-Ahad',
      'The One and Only — utterly unique, without any equal.',
      'الأحد'),
  WordEntry('ALMUTI', 'Al-Mu\'ti',
      'The Giver — the true source of every gift His creation receives.',
      'المعطي'),
];
