import 'word_bank_entry.dart';

/// The 25 Prophets traditionally named in the Qur'an, in the app's existing
/// "Hazrat Ibrahim (Abraham)" Latin-name convention.
const kProphetNames = <WordEntry>[
  WordEntry('ADAM', 'Adam',
      'The first human being and prophet, created by Allah and taught the names of all things.'),
  WordEntry('IDRIS', 'Enoch',
      'Known for his wisdom, and said to be the first to write with a pen.'),
  WordEntry('NUH', 'Noah',
      'Built the Ark and preached for 950 years, saving the believers from the great flood.'),
  WordEntry('HUD', 'Hud',
      'Sent to the people of \'Ad, who were destroyed by a fierce, roaring wind for their arrogance.'),
  WordEntry('SALIH', 'Salih',
      'Sent to the Thamud people with a miraculous she-camel as a sign from Allah.'),
  WordEntry('IBRAHIM', 'Abraham',
      'Known as the "Friend of Allah"; rebuilt the Kaaba together with his son Ismail.'),
  WordEntry('LUT', 'Lot',
      'Warned his people against their sinful ways before their city was destroyed.'),
  WordEntry('ISMAIL', 'Ishmael',
      'Ibrahim\'s son, whose willingness to be sacrificed is remembered every Eid al-Adha.'),
  WordEntry('ISHAQ', 'Isaac',
      'Ibrahim\'s second son, born to Sarah in her old age as a promised blessing.'),
  WordEntry('YAQUB', 'Jacob',
      'Father of the twelve tribes and of Yusuf; wept for years over his lost son.'),
  WordEntry('YUSUF', 'Joseph',
      'Sold into slavery by his brothers, he rose to become a trusted ruler of Egypt.'),
  WordEntry('AYYUB', 'Job',
      'A model of patience, enduring years of illness and loss without losing faith.'),
  WordEntry('SHUAYB', 'Shuayb',
      'Sent to the people of Madyan to warn them against cheating in trade.'),
  WordEntry('MUSA', 'Moses',
      'Led the Israelites out of Egypt and received the Torah on Mount Sinai.'),
  WordEntry('HARUN', 'Aaron',
      'Musa\'s brother and helper, appointed to support him in delivering the message.'),
  WordEntry('DHULKIFL', 'Ezekiel',
      'Known for his patience and for faithfully keeping his promises.'),
  WordEntry('DAWUD', 'David',
      'Given the Zabur (Psalms) and blessed with a beautiful voice and great strength.'),
  WordEntry('SULAIMAN', 'Solomon',
      'Dawud\'s son, granted a kingdom and the ability to understand the speech of animals.'),
  WordEntry('ILYAS', 'Elijah',
      'Called his people back to worshipping Allah alone instead of the idol Baal.'),
  WordEntry('ALYASA', 'Elisha',
      'Continued the mission of Ilyas, guiding his people with patience and wisdom.'),
  WordEntry('YUNUS', 'Jonah',
      'Swallowed by a whale after fleeing his people; Surah Yunus is named for him.'),
  WordEntry('ZAKARIYA', 'Zechariah',
      'Prayed for a child in his old age and was blessed with his son Yahya.'),
  WordEntry('YAHYA', 'John',
      'Born to Zakariya as an answered prayer, known for his piety from childhood.'),
  WordEntry('ISA', 'Jesus',
      'Born miraculously to Maryam and given the ability to perform miracles by Allah\'s permission.'),
  WordEntry('MUHAMMAD', 'Muhammad',
      'The final prophet, who received the Qur\'an and completed the message for all mankind.'),
];
